### ISSUE TITLE
No signal 

### ISSUE THREAD

**Issue by wojtulab** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#11]
I am loosing my signal every one minute for a few seconds.
Option 'Record Call' disappear in phone call settings after first call with recording 

OnePlus5 Android 9.0.3
Magisk 18.1
Magisk Manager 7.1.1
Unfortunately uninstallation doesn't help me.

![Screenshot_20190403-200427](https://user-images.githubusercontent.com/14801148/55502036-fd141b00-564b-11e9-9c19-db0d3d5df478.jpg)

**Comment by shadowstepxda** [comment]
The module was recently updated for Magisk 19. Please update your Magisk, that should help. Additionally, please uninstall the module, reboot your phone, redownload and install the module again from Magisk Manager itself. It should work. :)

Regarding signal issues, that is something totally unrelated to the module, so that is something I can't help you with, sorry!
