### ISSUE TITLE
Don't work on OOS 11 for OP7T

### ISSUE THREAD

**Issue by FishMagic** [Magisk-Modules-Repo/OOSNativeCallRecordingEnabler#20]
After update to OOS 11 on my OP7T, when enable this module will cause all the SIM card cannot register to the network.

**Comment by Narkoleptika** [comment]
Same here on OP7PRO. What's strange is that it initially worked after the update, but about a week and a reboot later, it's no longer working.

**Comment by Taknok** [comment]
Same issue here, OOS 11 worked fine, I also did multiple reboots without issue. Then I installed magisk 23 and after reboot `com.android.phone` keep crashing.

This is probably due to permission, because doing those commands fixed the bug 30s for me: https://github.com/topjohnwu/Magisk/issues/2880#issuecomment-794734361

**Comment by shadowstepxda** [comment]
@FishMagic @Narkoleptika @Taknok Not sure if OnePlus changed something in OOS 11. I have a OP5, and we don't have OOS 11, obviously, so can't even test myself. Did you guys follow the right steps before updating?

Uninstall the existing module -> Reboot -> Download and apply the system update -> Reboot -> Download and install the latest module -> Reboot your phone again once the installation is complete.

_Note: disabling and enabling the module is different than uninstalling and reinstalling in this module's case._

I also tried checking if Magisk changed something that probably broke it, but couldn't find anything. I am on latest Magisk (v23.0) myself and it works just fine for me, even across multiple reboots.

You guys can always try a different method from my [XDA thread](https://forum.xda-developers.com/t/3634292/), or give [jOnePlus Tools](https://play.google.com/store/apps/details?id=net.jroot3d.joneplustools) a shot. Hopefully one of the method works.

**Comment by Narkoleptika** [comment]
Hi I just wanted to add that I did follow the right steps before updating (uninstalled, not disabled before OTA). Also I'll confirm I'm on latest magisk (23) as well.

Interestingly, I looked at the jOnePlus Tools link you provided and the top review says the app worked until the most recent update (presumably OOS 11). According to them there's a new phone and recorder app.

![Screenshot_20210523-012317](https://user-images.githubusercontent.com/7088166/119253476-44303380-bb66-11eb-88f1-8d328a4eba4a.jpg)

**Comment by Taknok** [comment]
I'm on magisk 23 and OOS 11 and I did `Uninstall the existing module -> Reboot -> Download and apply the system update -> Reboot -> Download and install the latest module -> Reboot your phone again once the installation is complete.` the issue is still present. I tried other unistall reboot or disable reboot disabled uninstall reboot etc etc. Still bugging.

The bug seems to be triggered when modifying the apk on this [line](https://github.com/nipunnarang/oosnativecallrecordingenabler/blob/7b1ecac94de63a4b70ca6362aee73ac925bcde41/common/install.sh#L19). Without the apk modification this issue is not triggered. But the apk reset the value and auto disable the recorder. 

I tried to look to the smali code, but I do not have the previous apk to do the comparison.

**Comment by Dennis-Q** [comment]
> @FishMagic @Narkoleptika @Taknok Not sure if OnePlus changed something in OOS 11. I have a OP5, and we don't have OOS 11, obviously, so can't even test myself. Did you guys follow the right steps before updating?
> 
> Uninstall the existing module -> Reboot -> Download and apply the system update -> Reboot -> Download and install the latest module -> Reboot your phone again once the installation is complete.
> 
> _Note: disabling and enabling the module is different than uninstalling and reinstalling in this module's case._
> 
> I also tried checking if Magisk changed something that probably broke it, but couldn't find anything. I am on latest Magisk (v23.0) myself and it works just fine for me, even across multiple reboots.
> 
> You guys can always try a different method from my [XDA thread](https://forum.xda-developers.com/t/3634292/), or give [jOnePlus Tools](https://play.google.com/store/apps/details?id=net.jroot3d.joneplustools) a shot. Hopefully one of the method works.

Just to let you know my experience; I follow the same procedure except that I skip the first reboot. 

- I only uninstall the module before I apply the system update, I do not even reboot after pressing uninstall the module in the app.
- after the ota install I apply magisk to the inactive slot

- then after the first reboot I install module 9.2 and after the last reboot all still works.

This is what I did today with the latest OOS11 for the OnePlus 7T (11.0.1.1 - with May security updates) and is working perfectly fine as well!

**Comment by Taknok** [comment]
Ok, I'm on 11.0.0.2, I will wait 11.0.1.1.

**Comment by Narkoleptika** [comment]
11.0.1.1 appears to have fixed the issue for me.

**Comment by FishMagic** [comment]
It can work on 11.0.1.1

**Comment by Taknok** [comment]
Issue is back after 5 days without issue after the update to 11.0.1.1

**Comment by Narkoleptika** [comment]
Can confirm. Updating to 11.0.1.1, then installing latest version of this module worked. Then after reading @Taknok's latest comment, I rebooted, and it's no longer working. Same thing that happened with the last update.

Makes me think that something that _is compatible_ is shipping with the OTA, then getting updated to something that _isn't compatible_. 

I wonder if reapplying the OTA update, then reinstalling the module would temporarily fix the issue until the next reboot after whatever it is gets updated again.

**Comment by Dennis-Q** [comment]
Since the update (7-days) I have rebooted my phone a couple of times (to disable/enable adblocking quickly) and have never experienced any issues with the call recording since applying the module.

So I do not recognize the problem you have. I have the EU-version of the OP7T / firmware 11.0.1.1, not sure if that is different for you? Still weird that it does work for days.. 

@Narkoleptika Could be a theory. My Phone app version is: 5.0.1.0.210507195213.2b405e0. Can you check yours?

**Comment by Narkoleptika** [comment]
Hmm seems to be the same version

version 5.0.1.0.210507195213.2b405e0

I have a NA model?? Not entirely sure, but I assume so since I live in the US.

I might try reapplying the update to test my theory later this week, but it's seeming like it might be something else causing the issue.

**Comment by Taknok** [comment]
I also have the EU version, I have a OP7. It did not bug directly.

Module was uninstalled since my bug. Then reboot to install OTA. Then install module and n°0 reboot. Two other reboot without issue (n°1 and n°2). Then third reboot (n°3), phone app crashing at boot and crash in loop, no sim code to enter.

It may be random at boot or shutdown or even during runtime. I did not do anything particular (no root modification, no module installation, just normal use)

**Comment by Taknok** [comment]
Build number for EU end with `BA`, world ends with `AA`, I don't remember India tag, and I don't know if there is more. ![Screenshot_20210601-094128](https://user-images.githubusercontent.com/12498020/120285645-bec32680-c2bd-11eb-8bf1-a2092afbba48.jpg)

**Comment by Narkoleptika** [comment]
First, here's my build, if that's helpful at all
![Screenshot_20210601-074857](https://user-images.githubusercontent.com/7088166/120343893-f0cc8c80-c2ad-11eb-8b96-c195be58f9bc.jpg)

Also, I reinstalled my current version with no magisk modules installed, reboot, installed call recording module, reboot. Still not working. I think that rules out my theory. At least as far as I'm able to test. It's possible that the previous version on the slot the OTA was installed on was 10.* had something to do with it but 🤷🏻‍♂️

**Comment by Taknok** [comment]
Here is the error message (with `logcat`) displayed only when plugin is installed:
```
AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.phone.PhoneApp" on path: DexPathList[[zip file "/system/priv-app/TeleService/TeleService.apk"],nativeLibraryDirectories=[/system/priv-app/TeleService/lib/arm64, /system/lib64, /system/system_ext/lib64, /system/lib64, /system/system_ext/lib64]]
```

Plugin without apk modification do not trigger the issue. So it is not an issue with permissions or magisk. Again, only the `sed` trigger the issue on 11.0.1.1.

**Comment by cubic3d** [comment]
Having this issue with current 11.1.1.1 on OnePlus 6 - reinstalled 9.2 after update to OOS 11 and it worked a couple of days and multiple restarts but crashed today as others already reported.

**Comment by Taknok** [comment]
Can you confirm it is crashing on OOS 9.2 ? (Not sure if you downgrade and re upgrade)

**Comment by Taknok** [comment]
Can someone send here the unmoded `TeleService.apk` (working when moded) from a previous oxygenos version ?
@nipunnarang for exemple if you still have your OP5.

**Comment by Taknok** [comment]
I know this issue is inactive an closed, but if someone want to continue the investigation. Main hypothesis is that it is due to change in the signing version of the apk. V3 signature signs also the "string" part, which v1 and v2 didn't. Thus modifying the apk result in a invalid apk now and breaks the system.

```bash
$ apksigner verify -v TeleService.apk
Verifies
Verified using v1 scheme (JAR signing): false
Verified using v2 scheme (APK Signature Scheme v2): false
Verified using v3 scheme (APK Signature Scheme v3): true
Verified using v4 scheme (APK Signature Scheme v4): false
Verified for SourceStamp: false
Number of signers: 1
```
